apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 40
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository}}:{{.Values.image.tag | default "latest"}}
        imagePullPolicy: 
        command: ["sh", "-c", "while true; do sleep 30; done" ]
        resources:
{{ toYaml .Values.resources | indent 10}}